# execute
./bin/oka_own_1 > oka_own_1.txt &
./bin/oka_own_2 > oka_own_2.txt &
./bin/oka_own_3 > oka_own_3.txt &
./bin/oka_own_4 > oka_own_4.txt &
./bin/oka_own_5 > oka_own_5.txt &
./bin/oka_own_6 > oka_own_6.txt &
./bin/oka_own_7 > oka_own_7.txt &
./bin/oka_own_8 > oka_own_8.txt &
./bin/oka_own_9 > oka_own_9.txt &
./bin/oka_own_10 > oka_own_10.txt &
./bin/oka_own_11 > oka_own_11.txt &
./bin/oka_own_12 > oka_own_12.txt &
./bin/oka_own_13 > oka_own_13.txt &
./bin/oka_own_14 > oka_own_14.txt &
./bin/oka_own_15 > oka_own_15.txt &
./bin/oka_own_16 > oka_own_16.txt &
./bin/oka_own_17 > oka_own_17.txt &
./bin/oka_own_18 > oka_own_18.txt &
./bin/oka_own_19 > oka_own_19.txt &
./bin/oka_own_20 > oka_own_20.txt &
./bin/oka_own_21 > oka_own_21.txt &
./bin/oka_own_22 > oka_own_22.txt &
./bin/oka_own_23 > oka_own_23.txt &
./bin/oka_own_24 > oka_own_24.txt &
./bin/oka_own_25 > oka_own_25.txt &
./bin/oka_own_26 > oka_own_26.txt &
./bin/oka_own_27 > oka_own_27.txt &
./bin/oka_own_28 > oka_own_28.txt &
./bin/oka_own_29 > oka_own_29.txt &
./bin/oka_own_30 > oka_own_30.txt &
